/**
 * Error envelope from docs/API_CONTRACT.md:
 * { "error": { "code": "VALIDATION_ERROR", "message": "...", "requestId": "..." } }
 */
export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
    requestId?: string;
  };
}

/** Codes generated by the client itself, never by the server. */
export type ClientErrorCode = "NETWORK_ERROR" | "INVALID_RESPONSE" | "UNAUTHENTICATED" | "DEMO_UNSUPPORTED";

export class ApiError extends Error {
  readonly code: string;
  readonly status: number;
  readonly requestId?: string;

  constructor(params: { code: string; message: string; status: number; requestId?: string }) {
    super(params.message);
    this.name = "ApiError";
    this.code = params.code;
    this.status = params.status;
    this.requestId = params.requestId;
  }

  get isUnauthenticated() {
    return this.status === 401;
  }

  get isForbidden() {
    return this.status === 403;
  }

  get isNotFound() {
    return this.status === 404;
  }
}

export function isApiError(value: unknown): value is ApiError {
  return value instanceof ApiError;
}

function isErrorBody(value: unknown): value is ApiErrorBody {
  if (typeof value !== "object" || value === null || !("error" in value)) return false;
  const err = (value as { error: unknown }).error;
  return (
    typeof err === "object" &&
    err !== null &&
    typeof (err as { code?: unknown }).code === "string" &&
    typeof (err as { message?: unknown }).message === "string"
  );
}

export function apiErrorFromResponse(status: number, body: unknown): ApiError {
  if (isErrorBody(body)) {
    return new ApiError({
      code: body.error.code,
      message: body.error.message,
      status,
      requestId: body.error.requestId,
    });
  }
  return new ApiError({
    code: status === 401 ? "UNAUTHENTICATED" : "INVALID_RESPONSE",
    message: status === 401 ? "Your session has ended. Sign in again to continue." : "The server returned an unexpected response.",
    status,
  });
}

/** Plain-language message that is safe to show. Never includes server internals. */
export function describeError(error: unknown): { title: string; detail: string; requestId?: string } {
  if (isApiError(error)) {
    if (error.code === "NETWORK_ERROR") {
      return { title: "Can't reach HealthHub", detail: "Check your connection and try again." };
    }
    if (error.isUnauthenticated) {
      return { title: "You're signed out", detail: "Sign in again to continue." };
    }
    if (error.isForbidden) {
      return { title: "You don't have access to this", detail: "Your account isn't permitted to view or change this item." };
    }
    if (error.isNotFound) {
      return { title: "Not found", detail: "This item doesn't exist or isn't available to you." };
    }
    return { title: "Something went wrong", detail: error.message, requestId: error.requestId };
  }
  return { title: "Something went wrong", detail: "An unexpected error occurred. Try again." };
}
